services:
  vesta:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: vesta:2.0.0
    container_name: vesta
    ports:
      - 443:5000
    volumes:
      - xxx:/vesta/ssl/cert.crt
      - xxx:/vesta/ssl/cert.key
      - ./output:/vesta/output
    environment:
      - vcenter=xxx